### ISSUE TITLE
INVITES: When users click X on 'join topic/join group', they get a blank screen

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1701]
**What is the problem?**

When you follow a URL share link to a public topic or public group, the join pop-up is over a blank page. 

![image](https://github.com/user-attachments/assets/3a9757bd-5bca-4553-8f7d-9cfc270aa5c8)

When you then click the 'X', if you don't want to join it, you are then left on a blank page: 

![image](https://github.com/user-attachments/assets/12a01ef8-3ad6-4ac2-85ce-5bba0796637a)

**Why is this a problem?**

Not very helpful for users. Plus doesn't give them any idea of what they're signing up to. 

**Possible solution.**

Related to [this](https://github.com/citizenos/citizenos-fe/issues/1376) and [this](https://github.com/citizenos/citizenos-fe/issues/1700) issue (which discuss the fact that new users need to see as much about what they're joining as possible to decide if they want to join), I'm thinking that for public topics and groups, the pop-up can be overlaid with the group or topic greyed out a little in the background. (As it's public anyway). Then if they click X, they are taken to that group/topic anyway, just without having joined it. 

For private topics, perhaps it can be overlaid over the dashboard, so then if the click X they land on the dashboard? 

I'm also thinking that it would be best if this pop-up was moveable in all cases (by clicking and dragging), so the user can move it out of the way to have a look at what's in the background, to help inform them that (hopefully) yes, they do want to join!  

![image](https://github.com/user-attachments/assets/83c4932b-7b43-4784-b328-b8c42a1d7959)

@kevincrepin @TiinaDUX @Lidziya-p what do you think? :)

**Comment by kevincrepin** [comment]
Logical to me to have this overlaying the dashboard and when closing the dialog window it keeps you there.

But it's not very common behaviour to be able to move this dialog window around. And wouldn't they have already seen the content of the group before pressing that "join group" action?

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ah re the last question - no, this is for invites via URL, so they've seen absolutely nothing yet at this point, this is the first thing they see (once we've swapped it with login).

For private topics, public topics, private groups and public groups - so we need to decide what they see behind the pop-up in each case, and where they are taken after clicking X :)

**Comment by kevincrepin** [comment]
What page this dialog opens up over:

- Not logged in: the landing page when not logged in
- Logged in: dashboard

I don't see a need to differentiate based on what they are invited to. It's gonna make things more complex and not sure if the value is really there? Let's say we do it in such a way that if you get an invite to a private topic, the screen behind the dialog is the private topics page. If you close now it's not like that private topic you were invited to (but didn't join because you pressed X) will be visible here. So I'm not sure if the added complexity of taking this approach actually pays off?
 
If you press X we can assume you don't want to deal with it and then the dashboard is a better "general starting point".

**Comment by BeccaMelhuish** [comment]
@kevincrepin I definitely see your point for private topics and groups, and think it makes sense it should be overlaid over the DB(logged in)/home(logged out), but for public ones it makes a lot of sense to me that it should be overlaid over the public topic/group.

**My reasons for this are:** 
- They may not feel ready to commit to 'join' something they don't yet see, and want to have a look around it before joining it. Often they will be just following the link to have a look - they are curious, want to see what it's all about, and will have not yet decided that they do actually want to participate. 
- For groups, they may not be confortable joining the group when they see it will make their email address visible to the admin(s). In a public group the admins may well be total strangers. Or they may fear lots of notifications if they 'join' something. But they may still want to access the group, check it out and even participate in the topics. So this gives them the option to do so while landing in the right place. Then later they can join the group when they feel more confident/keen to.
- Users in tests have shared/shown the feeling that 'join' is a big commitment early on and could be a barrier to entry. Which to my mind makes a lot of sense. Users aren't necessary very engaged initially, but it's in the process of participating that they then become engaged. 

Actually, I'm reminded now that we did decide [here](https://github.com/citizenos/citizenos-fe/issues/1551) that we would remove the 'join' pop-up entirely for public topics, and just have it for public groups. So this solution would be a kind of compromise between the two, just for groups? 

**In which case, the solution would be:** 
- For private topics/groups not logged in: pop up over logged out landing page
- For private topics/groups logged in: pop up over DB
- For public topics: no pop-up, get prompted to log in when they engage and automatically added to the topic when they have engaged (or clicked join) 
- For public group: pop up over public group

@kevincrepin wdyt? :)

**Comment by kevincrepin** [comment]
I feel that if the main problem to solve here is the "I don't wanna join yet, but I want to see what this is about" then I'd rather have a secondary button "view without joining" instead of making the "close window" the main flow to solve that problem.

![Screenshot 2024-11-29 at 15 21 53](https://github.com/user-attachments/assets/e112332f-1f44-445b-bdc8-bf01f87c393d)

And then I would say it could still follow the logic of always opening in the dashboard :D Then we don't need to make an exception on this.

**Comment by BeccaMelhuish** [comment]
@kevincrepin Oh nice, how much simpler that is! :D 

Wdyt re public topics - do we do the same thing, or stick with previous decision to not have a pop-up at all? 

And I guess here we need to change it to: 

'To **join** this group' (or topic) etc

![image](https://github.com/user-attachments/assets/ecad0226-e836-4cea-9f5b-cb1701667263)

**Comment by kevincrepin** [comment]
I would here again say that unless it's a massive barrier it would be nice to have the same behaviour, so we have less exceptions and the user gets used to the behaviour pattern.

Yep, I'll update the text :)

**Comment by BeccaMelhuish** [comment]
That makes sense, let's trial it like this for now then! :) 

**Dev task summary:** 

When a user follows a URL share link and gets a join pop-up: 
- [ ] For any link when logged out, it should be overlaid over the landing page
- [ ] For any link when logged in, it should be overlaid over the DB
- [ ] For public groups, there should be a 'View group without joining' button that takes them to the group
- [ ] For public topics, there should be a 'View topic without joining' button that takes them to the topic
- [ ] Make sure this doesn't go live without this being fixed too: https://github.com/citizenos/citizenos-fe/issues/1706

**Comment by ilmar** [comment]
Hi!
Could you please stop tagging me in this project? I’ve been receiving notifications for several years now. I have no connection to citizenOS; you need @ilmartyrk 
Thanks! :)

**Comment by BeccaMelhuish** [comment]
Apologies @ilmar!! Thanks so much for bringing this to our attention.

**Comment by ilmartyrk** [comment]
Estimate 6h. Might be some difficulties related to moving the  popup in the routing process, but might not.

**Comment by DiverVM** [comment]
@ssin1901 First iteration of invitation flow already merged and can be tested
I made everything according to this doc -> https://docs.google.com/document/d/1dv-wrjQf9iN5daq2dbXcCscSLR2xSqSfNbTS9rIcRGU/edit?tab=t.0#heading=h.3oozgur53bfn

I left there notes like `( local + / dev ? / test ? / prod ? )` for every case I checked, means locally I checked and it works as per doc. If you don't find them useful then please feel free removing them.

@ssin1901 @BeccaMelhuish next step I plan to make a redesign of components as per https://github.com/citizenos/citizenos-fe/issues/1376

**Comment by BeccaMelhuish** [comment]
@ssin1901 when testing please check that the 'Accept' privacy policy pop-up is still there and all working OK for new registrations in this flow :)

**Comment by ssin1901** [comment]
@BeccaMelhuish @DiverVM the join topic buttons worked as intended when the user is logged out, clicks join topic and logs in (see screen recording).

1.https://github.com/user-attachments/assets/df18f3fe-ce60-4be0-a0f7-7adb5fe6559d

**However,** when a user follows a share link (screenshot1) and then creates a new account, when they go to their inbox and verify their email (screenshot2), they get taken to this blank screen which has the correct topic URL but no topic view (screenshot3).

<img width="1405" alt="Image" src="https://github.com/user-attachments/assets/b932dc96-c722-4ec8-9404-6c733b261840" />

<img width="1401" alt="Image" src="https://github.com/user-attachments/assets/a85d5553-a218-4ab7-a0ff-8c75cf674835" />

<img width="1413" alt="Image" src="https://github.com/user-attachments/assets/13c7a1b9-5c8e-427f-89e2-2779c6494fc7" />

Also in development.app.citizenos.com when I create new users and verify their accounts (email + password) then the account is created without me needing to accept the Terms and Conditions. However when I login with Google then I'm asked to accept the Terms and conditions. Is this supposed to happen?

**Comment by DiverVM** [comment]
thanks @ssin1901 let me check and fix this case. Please keep updated with new possible issues

**Comment by BeccaMelhuish** [comment]
@ssin1901 @DiverVM just to confirm that we should make sure new users accept the legal stuff through whatever means they arrive :)

**Comment by DiverVM** [comment]
@

**Comment by DiverVM** [comment]
@ssin1901 fixed with the scope of https://github.com/citizenos/citizenos-fe/issues/1376

**Comment by ssin1901** [comment]
@BeccaMelhuish @DiverVM the blank email issue seems to be resolved. When the user follows the activation link from their email (screenshot1), they get prompted to login (screenshot2) and then after successfully logging in, they get taken directly to the topic without the join topic popup (screenshot3).

However, user is still not prompted to Accept Terms and Conditions. Should I make a new issue for that?

![Image](https://github.com/user-attachments/assets/5a2a51c5-d038-4649-a998-eb7ea09492a1)

![Image](https://github.com/user-attachments/assets/6bc34561-c3d8-401d-a723-4fe03b872eee)

![Image](https://github.com/user-attachments/assets/cfac13ab-8704-4d37-a291-1d7cbd154233)

**Comment by ssin1901** [comment]
@BeccaMelhuish very nice thing - logged out user does not see the admins name (screenshot1), but the logged in user does (screenshot2, screenshot3).

![Image](https://github.com/user-attachments/assets/be1816f4-76e4-42bc-b701-5d9580d330d1)

![Image](https://github.com/user-attachments/assets/e800adea-2c91-40b9-8bac-ad25dcac4143)

**Comment by ssin1901** [comment]
@DiverVM @BeccaMelhuish as per today's meeting (14.02.2025) if then if the public share link doesn't have a blank screen as a background and has the correct options, sending it to Ready for Pre-Live
