### ISSUE TITLE
IDEA GATHERING: Enable admins to set a template for ideas input

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1822]
This solution hasn't been confirmed by Story of Estonia yet, but I think with turnaround being tight let's go ahead with the design already as it's a feature that would be useful to add anyway. 

So @kevincrepin @Lidziya-p @TiinaDUX would you be able to provide design for a feature to enable admins to add a template text like Github does, for example here: 

![Image](https://github.com/user-attachments/assets/a568fbbf-c945-4d8c-bbab-4b9c33466ab4)

Like on Github, the text will stay in place when you type, so you just add to it (i.e. not the kind that disappears when you start typing). 

I guess this would be another one to add under the 'Advanced' settings for idea gathering?

**Comment by kevincrepin** [comment]
I agree it could go under the advanced settings, otherwise it gets more prominence and it seems to be more of a power user function.

![Image](https://github.com/user-attachments/assets/a53690eb-4785-472f-968e-a0cbc8462b7b)

https://www.figma.com/design/ODWxKEHuAt3DGkrJwRZJ8a/Platform-2.5---Design?node-id=645-70531&t=f5jUsXli3piEh8jM-1

Still has the old copy tho :)

**Comment by BeccaMelhuish** [comment]
Great thank you @kevincrepin! And presumably the admin writes in the 'Write' box right there then, in order to add in the template? But if it's turned to OFF they're unable to type in there, or the whole box is greyed out perhaps?   

And I guess no need to have a character limit for the template, as we no longer have one for ideas? (Seems like extra work, maybe not necessary)

**Comment by kevincrepin** [comment]
Yes, the admin would compose the template format in the text box. I would completely hide the text box if this setting is turned off – again not to give it too much prominence.

Example:

![Image](https://github.com/user-attachments/assets/4ec8b16e-382f-4468-a04c-7ea66df8c259)

I updated the design so that the character limit is removed.

**Comment by BeccaMelhuish** [comment]
Ah perfect yes that makes sense, thank you!

**Comment by BeccaMelhuish** [comment]
**So Dev task summary:** 

- Implement as per the two designs above.
- Slight correction to the copy 'You can create a template to give participants guidance on how to compose their idea'
- Don't include a character limit
- Make sure the template text remains in place once the participant starts typing (doesn't disappear) 

@ilmartyrk or @DiverVM would you be able to give an estimate? :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk @DiverVM: 

A question from Story of Estonia: 
_Would it be possible if a person fills in the data in the first questions, it is automatically filled in the next ones?
It is too much to ask from one person to fill in the same thing 5x, that will decrease the motivation._ 

Do you have any ideas? I also posted about this [on Slack](https://citizen-os.slack.com/archives/C02M6JLEGP3/p1738231616258729) with some thoughts from me, so we can discuss more there if easier.

**Comment by BeccaMelhuish** [comment]
Discussed in product meeting, will go ahead as per [task summary](https://github.com/citizenos/citizenos-fe/issues/1822#issuecomment-2618210621) above :)

**Comment by BeccaMelhuish** [comment]
Rough estimate: up to 1 day for the whole thing.

**Comment by DiverVM** [comment]
@BeccaMelhuish @ssin1901 idea template UI is on dev, can be tested
API implementation is here -> https://github.com/citizenos/citizenos-api/pull/398

If I don't manage how to update DB, then we probably need to wait Ilmar, let's see

**Comment by BeccaMelhuish** [comment]
Thank you @DiverVM! Tested and a couple of issues I found: 

1. 100 characters is too small - let's have it unlimited :)  

![Image](https://github.com/user-attachments/assets/96c63d84-0cb8-4a73-bab7-8a20da2d150f)

2. There seemed to be a link between adding the text in the template part in tab 3, and the topic title I added in the tab 1:
- I added a title in tab 1
- I added text in the template box in tab 3
- When I went to 'Continue' it was greyed out so I couldn't proceed
- I then went back to tab 1 and saw the title was no longer there
- Once I added the title back in, the template text disappeared

**Comment by DiverVM** [comment]
@BeccaMelhuish fixed

**Comment by BeccaMelhuish** [comment]
@DiverVM tested and I still had a short character limit, but I know sometimes there's a lag so will leave it closed for now and try again in a bit :) 

![Image](https://github.com/user-attachments/assets/03221d6a-7244-41c1-8787-7adc7ce819d7)

**Comment by DiverVM** [comment]
hm, interesting

**Comment by ssin1901** [comment]
@DiverVM getting the same issue with the character limit (screen recording 1). 

Also the template settings don't get saved but @DiverVM  @BeccaMelhuish - is this related to the database access (screen recording 2)


https://github.com/user-attachments/assets/0aa9b952-2c66-43d1-a3d2-d79ddae93a03

https://github.com/user-attachments/assets/82afdc1d-bcea-4b29-8980-763abd74dc86

**Comment by DiverVM** [comment]
@BeccaMelhuish @ssin1901 DB updated, templates are working as expected, can be tested full functionality.
I will check the issue with limitation

**Comment by DiverVM** [comment]
fixed limit

<img width="1099" alt="Image" src="https://github.com/user-attachments/assets/ee5d057e-83ab-4b8f-9e35-0cd2a32e7197" />

**Comment by BeccaMelhuish** [comment]
Amazing! Testing and it's working beautifully! 

![Image](https://github.com/user-attachments/assets/51fb416e-a339-4b46-b995-32f8ec40be13)

Only small issue is that when I then go into 'Edit' and back to the Idea gathering tab it looks like this initially: 

![Image](https://github.com/user-attachments/assets/5a90f102-54ba-41e8-9ef3-d9b92e19a50e)

Then if I turn it on it's blank for a while, but then after a few seconds the text does usually appear:  

![Image](https://github.com/user-attachments/assets/662b9b8a-7c50-4fa3-ab83-616d844e3dab)

But this should be totally fine for today :)

**Comment by BeccaMelhuish** [comment]
Putting this one back to in progress now, and also to fix it so that formatting that's set (bold, italic, bullets etc) by the admin in the template carries through to the idea :)

**Comment by BeccaMelhuish** [comment]
@DiverVM Checked the video and can confirm the formatting issue was just user error (/unrelated UX issue), but I checked the editing issue and I still have the same thing happening in dev as [described here](https://github.com/citizenos/citizenos-fe/issues/1822#issuecomment-2655698984) (though this time the text never appeared when I turned it on) :)  

![Image](https://github.com/user-attachments/assets/81029df9-ce9b-4e1b-8dbc-f3aa0332911f)

**Comment by DiverVM** [comment]
@BeccaMelhuish fixed, let's give this ticket another try for testing

**Comment by ssin1901** [comment]
@DiverVM @BeccaMelhuish if there is no text in idea gathering template then it is switched off (screenshot1, screenshot2) when the user goes back to edit the topic. But if there is text then it is switched on (screenshot3, screenshot4).

1.1 Creation Mode (no text in template)
![Image](https://github.com/user-attachments/assets/ecaf4898-50bb-42ab-ae8d-f246030d16d6)

1.2 Edit Mode (no text in template)
![Image](https://github.com/user-attachments/assets/a1f66105-957f-407b-b6f5-9276c0f692d9)

2.1 Creation Mode (text in template)
![Image](https://github.com/user-attachments/assets/1a367830-4c7a-487f-bfb1-d85dcc9a29db)

2.2 Edit Mode (text in template)
![Image](https://github.com/user-attachments/assets/51554b9e-2b6d-4a42-8677-b287005ee3b2)

**Comment by ssin1901** [comment]
@DiverVM @BeccaMelhuish is the fixing formatting still in progress? (screenshot1). Does it need a separate issue?

![Image](https://github.com/user-attachments/assets/6c5306e7-1252-4fcf-b6b9-452625b65b13)

**Comment by BeccaMelhuish** [comment]
Great, sending to ready for pre-live! 

And re the formatting, unfortunately that isn't a bug but how it's meant to be (given that we have to use markdown for formatting, no better solution currently).
