### ISSUE TITLE
Test C888: Topic creation tabs displaying incorrectly/confusingly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#363]
On mobile, android, chrome, when creating a discussion topic, the tabs at the top (for the steps of creation) are displaying strangely. 

The headings don't show, just numbers, and it looks like it's on the 4th tab, rather than the first (where it should be), and the little "/" dash seems like an error? 

Wondering if the latter is a design issue rather than a bug, but to me the box around the little person icon on the right looks like a tab (so as above it feels like I'm on the 4th tab, though I see now there is a subtle line under the first one), and the person icon with the dash and the 1 doesn't say anything to me - am confused what it could be/mean.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a1f34b88-f933-46b1-95a3-bf70c4becf6b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I've fixed the tab sizes and alignment, but the person icon is meant for inviting users and it is as per design
https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=42%3A11279&mode=dev

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK yes I see.

So on the two different points:
- Re it looking like the words are missing from the tabs, I think in the design it's clearer that it's intentional because the numbers take up more of the space, the little blue line goes all the way across the space for the tab, and the number is centred rather than being to the left. This also makes the fact that tab 1 is selected a little bit clearer, as it the blue underline is more visible. 
- Re the invite co-creators tab looking like it is the one that's selected, @kevincrepin I wonder if you have any other design idea for adding co/creators that would get around this problem? The number next to the person icon also confuses things a bit, as it looks like the tabs are numbered 1 2 3 1, or 1 2 3 3. Plus on mobile the little pencil icon next to the person isn't visible, so it just looks like a tiny forward slash next to them, which again is quite confusing. 

This also makes me think, @kevincrepin do we want to be encouraging or even allowing people to click between the tabs at this point, or would be rather they use the "next" button to click through steps 1 to 3? Or is it more that we just want to indicate with the numbers where they are in the process of creating it, but they have to go through them in a linear fashion? (I feel like that's more common for such processes, and might get less messy?) 

Design:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/11720538-d2bc-4f43-b830-f2471b205685)

On my phone (android, chrome): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/18023291-6489-462f-97e3-7eccd01eb684)

**Comment by kevincrepin** [comment]
1. The numbering serves the double purpose of showing the (potential) linear process, but same as in desktop people can jump between the steps if they want.
2. About the co-editors, I understand your point. I'm thinking one way to solve it would be to take it out of the steps/tabs entirely and have it as a first section above the different steps' content. Made a quick example of how that could look/work:
![Screenshot 2023-11-21 at 18 16 43](https://github.com/citizenos/citizenos-fe/assets/26792281/ae4d81d8-daea-4456-ba6b-5cb7eb682444)

**Comment by BeccaMelhuish** [comment]
@kevincrepin what do you think about including the words in the tabs on mobile as well - 1. Compose 2. Settings 3. Preview - would there be space now there's only the 3 tabs, or still too cramped? I feel like this could help with [this issue](https://github.com/citizenos/citizenos-fe/issues/366) too, of thinking the preview is the real thing when creating on mobile? 

I like that solution for the co-creators myself! Though just thinking about the heading, thought process as follows:
- When there was zero co-creators, it would need to say "Add co-creators" or similar I think?
- For translatability I understand from @oksks that anything with a number like this would need to be written "Co-creators: 6" which would be a bit ugly I feel? 
- So maybe the label should just be "Add co-creators" always and not specify the number? Or with a little 6 in a circle (or however you think works) next to "Add co-creators" / some other way to indicate how many? 

And just to check, would this drop-down section be at the top of only Step 1, or would be present in the other tabs too?

**Comment by kevincrepin** [comment]
It just about fits in English, but I doubt in other languages that it would, I'm afraid...

It's actually a good question whether it shows on all steps because I assume that co-creators have the admin role in a topic? So they can also change settings etc. If so then I would show it in every step, yes.

I would prefer to still show the count of co-creators instead of a cta to invite (also after you've invited already). Feels like you haven't engaged yet with this although you have.

I updated here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=9715%3A85685&mode=design&t=PhFtA9pToszSoRt5-1

**Comment by oksks** [comment]
The "Compose. Settings. Preview" tab bit will spread onto 2 rows in mobile view in translation (Russian, in comparison, will be "Составить. Настройки. Предпросмотр"). Maybe could be solved via icons instead of words?

**Comment by kevincrepin** [comment]
Quickly tried out with icons (with and without numbers): https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=9722%3A94332&mode=design&t=PhFtA9pToszSoRt5-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin nice yes this is a good solution I think! (It's cleaner without the numbers, but I think they're important for orienting the user in the 3-step process?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9a8f22ff-0fbf-4698-8513-307d88ad17a7)

And this doesn't look so ugly as I thought it would :D 
So it would be "Invite co-creators" when there are zero, but as soon as there is 1 or more, it's like below, right? :) 
And at all steps in the process makes sense to me too (they are either admin or editors if I remember correctly, but either way they can edit at all the steps).  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f3d1e005-c254-4826-a25f-82861ff0279a)

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk @anettlinno, actually I just realised it's not quite right that everyone who's invited can edit all of these steps, as according to what we have in the HC, editors aren't able to change the visibility of topics public/private (which is one of the settings in Step 2): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fcece46c-594d-447a-9534-9a74f3a21570)

And currently we have it so that co-creators can be given either admin or edit rights: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/df5718eb-ede3-4e0b-ab4d-694558dcc483)

So I guess we have 3 options? 

- Either we make co-creators only able to access Step 1 (that feels very messy though)? 
- We let them access everything, but there's some sort of indication (greyed out, "you don't have adequate permissions") on the visibility field
- We make it so that all "co-creators" need to be admins, and only give this option when inviting.

**Comment by BeccaMelhuish** [comment]
Ah, also the fact that only admins can invite/share could cause issues here too, if you're invited as a co-creator with only edit rights (as inviting other co-creators, adding to a group, etc., wouldn't be possible but are part of this process):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/40505498-7f25-4680-b180-2be3003f4527)

**Comment by BeccaMelhuish** [comment]
So I guess best option is this one? 

- We make it so that all "co-creators" need to be admins, and only give this option when inviting.

**Comment by kevincrepin** [comment]
Can also do it so that co-creators / editors can only edit topic title, text, attachments, but not any settings, including categories and hashtags. This way we can disable the other steps and co-creator/editor can't even access those. Or like @BeccaMelhuish said, they can access but everything is disabled for them.

**Comment by BeccaMelhuish** [comment]
Though sometimes a co-creator is an admin (and the option for them to be added as an admin should be kept I think, as would be annoying to not be able to give admin rights to someone you want to already at this stage), would that confuse things? Or basically if you are added as an editor at this stage you can see/access certain things here, and if you're added as an admin you can see/access it all? 

I think maybe disabling rather than hiding completely is good, so they can see what they can't access, and then if they want to request admin rights to be able to access that bit too then they can do so (somehow - not sure how?). In case the initiator made an error in their permissions (as they didn't know the difference between editor and admin - quite possible tbh).

**Comment by BeccaMelhuish** [comment]
Oh, actually I just realised we'll need this editor view of this bit anyway, for when an editor goes to "Edit topic" :) 
So yeah, personally my vote is for showing all of it, but showing some is disabled due to permissions, and having a clear way of them requesting a 'permissions upgrade' if they want/need one. (Not sure how they do that currently in a topic generally? It doesn't spring to mind).

**Comment by anettlinno** [comment]
Good discussion above, @BeccaMelhuish and @kevincrepin!
We definitely need both, admin and editor roles among co-editors. 

To give a little bit background information (from our current use cases) and think from the roles perspective then

- **Admin** is a person(s) who organizes the whole discussion, they set the "rules" for the discussion. And therefore admins have an access to everything.
- **Editor** is a person(s) who is invited to work with the text -- to co-create the content or the discussion/voting topic and one should only have an access to text editing.

According to what was discussed above and what I think then editor should: 
- have an access to "Compose" features and "Preview" (but one should not have topic publishing rights) 
- not have an access to any topic settings and this tab could be disabled for editors
- see co-creators but not invite co-creators themselves (I think it would best if they don´t have "Manage" and "Invite" buttons, but they only see who are co-editors)
- invite and share people in the discussion AFTER the topic has published 
- not have a right to manage participant (change their permissions etc)
- not have an access to send discussion on the next phase and not have a right to set up voting settings
- have right to invite topic into the group
- have an access to "Edit topic" button in drop-down menu (in published topic view)

**Comment by BeccaMelhuish** [comment]
@anettlinno I'm thinking this would be great to have sorted before testing / as early on in the testing as possible :) 
(Though to be fair, the 'editor' role doesn't often get used according to the stats Ilmar provided, so may well not get used in the tests either, unless pushed). 

Does it need a set of designs from Kevin to make it clear for Ilmar how both the 'Edit' tabs and the topic itself should look from an editors perspective? 

Some thoughts on your list though: I'm wondering if editor should be allowed to invite and to add topics to a group? As in the current system they don't have rights to do this, and to me it confuses the distinction between editor and admin a bit? (Currently editor just edits, but inviting and adding to groups are more administrative things).

**Comment by BeccaMelhuish** [comment]
And summarising what I think the tasks are, as it got a bit complex: 

As per Kevin's designs [here](https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=9722%3A94332&mode=design&t=PhFtA9pToszSoRt5-1):

- [x] Change the mobile view of these Create tabs to be like this: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f47451ca-34e9-4cf5-b97a-5249f7718142)

- [ ] With this bit like this when more than 0 co-creators added:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9f2d07cd-f472-4022-bd14-d5174400f5eb)

Then the rest is still under discussion/design: 

- disabling certain settings for editors' view (necessary for Phase I)
- adding a way for editors to request admin rights, if you agree it's needed/useful there (could be a phase II thing).

**Comment by anettlinno** [comment]
I we all agree with co-editor roles and permissions then @kevincrepin I think we are missing following designs for "editor":

1. Disabled "Settings" preview with a mesage "Sorry, editors don´t have a permission for topic settings...". @kevincrepin @BeccaMelhuish please help with the text :)
2. How does the preview look like if they don´t have publishing rights? Shall we disable the "Publish topic" button or remove it entirely?
3. Remove "Invite co-creators" option and replace it with "See co-creators" option (should we also change the text there? 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/e618ae41-cbca-41e1-bd53-bb31b6e1b880)

Please do the same also in drop-down menu when topic is published:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/443a6672-e6c3-4542-81c9-afc0f1795f9b)

@BeccaMelhuish regarding allowing editors to add topic to the groups. I was thinking about the use case where you invite me to co-create topic and as we both have groups with similar interests (but aimed for different people) then after I have helped to put together the topic text, I also want to share it in my group. BUT I think this could be left on Phase II if not later... So, let´s take this out from the list for now :)

**Comment by anettlinno** [comment]
Let´s do these things in Phase I and leave requesting different role in Phase II.

**Comment by BeccaMelhuish** [comment]
@anettlinno yes I think good to leave the adding to a group to phase II, as if I remember correctly there is a feature where you can "request to add topic to a group" that will come in Phase II? If so, maybe this will cover that need anyway :) 

Re the rest of the rights though, what about inviting people? As in your list above you have that they're not able to invite co-creators, but that they are allowed to invite people once the topic is published. And currently in the existing platform, only admins can invite, so this would be a change to the current editor role. 

I'd argue for not allowing them to invite at all, as they are "editors" so should be able to only edit. But this could also be reviewed in Phase II if we saw there was a need for it for some reason (that wouldn't be solved by the potential "Ask for editor permissions" feature in Phase II)?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno Changed the stiles for mobile, but won't display list of editors at this point, not sure how would be correct as we don't have the Online/offline/not-accpted functionalities as in figma designs. Also would need actual clarification about what do add in Phase I and what not

**Comment by anettlinno** [comment]
Triage 96.
@kevincrepin we would need your design for **admin** co-creators view:
- joined
- pending
As currently we don´t have an option to separate online/offline users as in current designs. 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/588cc42e-0b76-40f4-9995-66dc8321b882)

@kevincrepin we agreed that **editors** cannot invite nor manage participants -- how would that look in the design? Removing "Manage" and "Invite co-creators" button or disable them?
AND if the list of co-creators gets very long, then how should this be solved? Either by "see more" or something else?

We are also missing design for disabled "Settings" preview with a message "Sorry, editors don´t have a permission for topic settings...". @kevincrepin we would need design for disabled page.

How does the preview look like if editors don´t have publishing rights? Shall we disable the "Publish topic" button or remove it entirely?

Let´s not allow editors to add topics in the group.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk nothing happens when I click anywhere on the new 'Invite co-creators' bar by the way :) 

Also wondering if this was just meant to be a design for mobile rather than also on desktop, but would need to check through the issue/designs - maybe @kevincrepin can confirm more easily :)   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dcfe72c2-a236-41cf-86a5-4acbc0be8ff5)

**Comment by anettlinno** [comment]
@BeccaMelhuish @ilmartyrk  that was only meant for mobile view. In desktop view it is as it was:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/a2b51626-1351-456a-af84-5618b224ae67)

**Comment by kevincrepin** [comment]
Exactly!

**Comment by ilmartyrk** [comment]
@anettlinno my bad, forgot to hide it from desktop and tablet

**Comment by ilmartyrk** [comment]
@anettlinno removed it from desktop views

**Comment by anettlinno** [comment]
Yes, now it´s all good. Closing this issue.

**Comment by BeccaMelhuish** [comment]
@anettlinno this does seem resolved re my original issue, but what about these design requests in your [earlier comment](https://github.com/citizenos/citizenos-fe/issues/363#issuecomment-1851615660) that came up along the way? :)

**Comment by BeccaMelhuish** [comment]
Reopening just so they don't get missed :)

**Comment by anettlinno** [comment]
Thanks, @BeccaMelhuish for noticing. I have created separate issue for that here: https://github.com/citizenos/citizenos-fe/issues/564
